insert into sources (name, kind, url) values
  ('Vercel Blog', 'atom', 'https://vercel.com/atom'),
  ('Next.js Blog', 'rss', 'https://nextjs.org/feed.xml'),
  ('React Blog', 'rss', 'https://react.dev/rss.xml'),
  ('OpenAI News', 'rss', 'https://openai.com/news/rss.xml'),
  ('GitHub Blog', 'rss', 'https://github.blog/feed/'),
  ('GitHub Changelog', 'rss', 'https://github.blog/changelog/feed/'),
  ('AWS News Blog', 'rss', 'https://aws.amazon.com/blogs/aws/feed/'),
  ('Cloudflare Blog', 'rss', 'https://blog.cloudflare.com/rss/'),
  ('Deno Blog', 'atom', 'https://deno.com/feed'),
  ('Bun Blog', 'rss', 'https://bun.com/rss.xml'),
  ('TypeScript Blog', 'rss', 'https://devblogs.microsoft.com/typescript/feed/'),
  ('Next.js Releases', 'github_releases', 'https://github.com/vercel/next.js/releases.atom'),
  ('React Releases', 'github_releases', 'https://github.com/facebook/react/releases.atom'),
  ('Hono Releases', 'github_releases', 'https://github.com/honojs/hono/releases.atom'),
  ('TypeScript Releases', 'github_releases', 'https://github.com/microsoft/TypeScript/releases.atom'),

  -- Anthropicは公式RSSが無いため、コミュニティ生成フィード(taobojlen/anthropic-rss-feed)で補完。
  -- 2026-07-06 動作確認済み(https://raw.githubusercontent.com/taobojlen/anthropic-rss-feed/main/anthropic_news_rss.xml)。
  ('Anthropic News (community feed)', 'rss', 'https://raw.githubusercontent.com/taobojlen/anthropic-rss-feed/main/anthropic_news_rss.xml'),

  -- Bluesky公式アカウント(2026-07-06 実在確認済み。運用実績のある公式ドメインハンドルのみ採用)。
  ('Vercel (Bluesky)', 'bluesky', 'https://bsky.app/profile/vercel.com'),
  ('Next.js (Bluesky)', 'bluesky', 'https://bsky.app/profile/nextjs.org'),
  ('Anthropic (Bluesky)', 'bluesky', 'https://bsky.app/profile/anthropic.com'),
  ('GitHub (Bluesky)', 'bluesky', 'https://bsky.app/profile/github.com'),
  ('Bun (Bluesky)', 'bluesky', 'https://bsky.app/profile/bun.sh'),
  ('Cloudflare (Bluesky)', 'bluesky', 'https://bsky.app/profile/cloudflare.social'),
  ('Deno (Bluesky)', 'bluesky', 'https://bsky.app/profile/deno.land'),
  ('TypeScript (Bluesky)', 'bluesky', 'https://bsky.app/profile/typescriptlang.org'),
  ('React (Bluesky)', 'bluesky', 'https://bsky.app/profile/react.dev'),
  ('AWS (Bluesky)', 'bluesky', 'https://bsky.app/profile/awscloud.bsky.social'),

  -- Hacker News経由で信頼済み公式ドメイン(apps/api/src/lib/trustedDomains.ts)の記事を発見する。
  ('Hacker News (trusted domains)', 'hn_domain', 'https://hn.algolia.com/api/v1/search_by_date?tags=story'),

  -- 2026-07-07 追加: 主要な言語・実行環境・フレームワーク・ライブラリの公式リリース/ブログ(全件動作確認済み)。
  ('Python', 'github_releases', 'https://github.com/python/cpython/releases.atom'),
  ('Rust', 'github_releases', 'https://github.com/rust-lang/rust/releases.atom'),
  ('Node.js', 'github_releases', 'https://github.com/nodejs/node/releases.atom'),
  ('Ruby', 'github_releases', 'https://github.com/ruby/ruby/releases.atom'),
  ('PHP', 'github_releases', 'https://github.com/php/php-src/releases.atom'),
  ('Kotlin', 'github_releases', 'https://github.com/JetBrains/kotlin/releases.atom'),
  ('Swift', 'github_releases', 'https://github.com/swiftlang/swift/releases.atom'),
  ('.NET', 'github_releases', 'https://github.com/dotnet/core/releases.atom'),
  ('Elixir', 'github_releases', 'https://github.com/elixir-lang/elixir/releases.atom'),
  ('Zig', 'github_releases', 'https://github.com/ziglang/zig/releases.atom'),
  ('Julia', 'github_releases', 'https://github.com/JuliaLang/julia/releases.atom'),
  ('Go Blog', 'atom', 'https://go.dev/blog/feed.atom'),
  ('Ruby News', 'rss', 'https://www.ruby-lang.org/en/feeds/news.rss'),
  ('Vue', 'github_releases', 'https://github.com/vuejs/core/releases.atom'),
  ('Svelte', 'github_releases', 'https://github.com/sveltejs/svelte/releases.atom'),
  ('Angular', 'github_releases', 'https://github.com/angular/angular/releases.atom'),
  ('SolidJS', 'github_releases', 'https://github.com/solidjs/solid/releases.atom'),
  ('Astro', 'github_releases', 'https://github.com/withastro/astro/releases.atom'),
  ('Remix', 'github_releases', 'https://github.com/remix-run/remix/releases.atom'),
  ('Nuxt', 'github_releases', 'https://github.com/nuxt/nuxt/releases.atom'),
  ('Qwik', 'github_releases', 'https://github.com/QwikDev/qwik/releases.atom'),
  ('Django', 'github_releases', 'https://github.com/django/django/releases.atom'),
  ('Django Blog', 'rss', 'https://www.djangoproject.com/rss/weblog/'),
  ('Rails', 'github_releases', 'https://github.com/rails/rails/releases.atom'),
  ('NestJS', 'github_releases', 'https://github.com/nestjs/nest/releases.atom'),
  ('Spring Blog', 'atom', 'https://spring.io/blog.atom'),
  ('PostgreSQL News', 'rss', 'https://www.postgresql.org/news.rss'),
  ('Redis', 'github_releases', 'https://github.com/redis/redis/releases.atom'),
  ('Redis Blog', 'rss', 'https://redis.io/blog/feed/'),
  ('Supabase', 'github_releases', 'https://github.com/supabase/supabase/releases.atom'),
  ('Kubernetes', 'github_releases', 'https://github.com/kubernetes/kubernetes/releases.atom'),
  ('Kubernetes Blog', 'rss', 'https://kubernetes.io/feed.xml'),
  ('Docker (Moby)', 'github_releases', 'https://github.com/moby/moby/releases.atom'),
  ('Docker Blog', 'rss', 'https://www.docker.com/feed/'),
  ('Terraform', 'github_releases', 'https://github.com/hashicorp/terraform/releases.atom'),
  ('Google Cloud Blog', 'rss', 'https://docs.cloud.google.com/feeds/gcp-release-notes.xml'),
  ('Azure Blog', 'rss', 'https://azure.microsoft.com/en-us/blog/feed/'),
  ('GitLab Blog', 'atom', 'https://about.gitlab.com/atom.xml'),
  ('Hugging Face Blog', 'atom', 'https://huggingface.co/blog/feed.xml'),
  ('Google DeepMind Blog', 'rss', 'https://deepmind.google/blog/rss.xml'),
  ('Vite', 'github_releases', 'https://github.com/vitejs/vite/releases.atom'),
  ('esbuild', 'github_releases', 'https://github.com/evanw/esbuild/releases.atom'),
  ('Webpack', 'github_releases', 'https://github.com/webpack/webpack/releases.atom'),
  ('Turborepo', 'github_releases', 'https://github.com/vercel/turborepo/releases.atom'),
  ('Rollup', 'github_releases', 'https://github.com/rollup/rollup/releases.atom'),
  ('Jest', 'github_releases', 'https://github.com/jestjs/jest/releases.atom'),
  ('Vitest', 'github_releases', 'https://github.com/vitest-dev/vitest/releases.atom'),
  ('Playwright', 'github_releases', 'https://github.com/microsoft/playwright/releases.atom'),
  ('Cypress', 'github_releases', 'https://github.com/cypress-io/cypress/releases.atom')
on conflict (url) do nothing;

insert into topics (slug, name_ja, name_en) values
  ('frontend', 'フロントエンド', 'Frontend'),
  ('nextjs', 'Next.js', 'Next.js'),
  ('react', 'React', 'React'),
  ('typescript', 'TypeScript', 'TypeScript'),
  ('javascript', 'JavaScript', 'JavaScript'),
  ('nodejs', 'Node.js / ランタイム', 'Node.js / Runtimes'),
  ('ai-llm', 'AI・LLM', 'AI & LLM'),
  ('dev-tools', '開発ツール', 'Developer Tools'),
  ('cloud', 'クラウド', 'Cloud'),
  ('aws', 'AWS', 'AWS'),
  ('cloudflare', 'Cloudflare', 'Cloudflare'),
  ('serverless', 'サーバーレス', 'Serverless'),
  ('devops', 'DevOps・CI/CD', 'DevOps & CI/CD'),
  ('security', 'セキュリティ', 'Security'),
  ('database', 'データベース', 'Database'),
  ('opensource', 'オープンソース', 'Open Source'),
  ('testing', 'テスト', 'Testing'),
  ('mobile', 'モバイル', 'Mobile')
on conflict (slug) do nothing;
