insert into sources (name, kind, url) values
  ('Vercel Blog', 'atom', 'https://vercel.com/atom'),
  ('Next.js Blog', 'rss', 'https://nextjs.org/feed.xml'),
  ('React Blog', 'rss', 'https://react.dev/rss.xml'),
  ('OpenAI News', 'rss', 'https://openai.com/news/rss.xml'),
  ('GitHub Blog', 'rss', 'https://github.blog/feed/'),
  ('GitHub Changelog', 'rss', 'https://github.blog/changelog/feed/'),
  ('AWS News Blog', 'rss', 'https://aws.amazon.com/blogs/aws/feed/'),
  ('Cloudflare Blog', 'rss', 'https://blog.cloudflare.com/rss/'),
  ('Deno Blog', 'atom', 'https://deno.com/feed'),
  ('Bun Blog', 'rss', 'https://bun.com/rss.xml'),
  ('TypeScript Blog', 'rss', 'https://devblogs.microsoft.com/typescript/feed/'),
  ('Next.js Releases', 'github_releases', 'https://github.com/vercel/next.js/releases.atom'),
  ('React Releases', 'github_releases', 'https://github.com/facebook/react/releases.atom'),
  ('Hono Releases', 'github_releases', 'https://github.com/honojs/hono/releases.atom'),
  ('TypeScript Releases', 'github_releases', 'https://github.com/microsoft/TypeScript/releases.atom'),

  -- Anthropicは公式RSSが無いため、コミュニティ生成フィード(taobojlen/anthropic-rss-feed)で補完。
  -- 2026-07-06 動作確認済み(https://raw.githubusercontent.com/taobojlen/anthropic-rss-feed/main/anthropic_news_rss.xml)。
  ('Anthropic News (community feed)', 'rss', 'https://raw.githubusercontent.com/taobojlen/anthropic-rss-feed/main/anthropic_news_rss.xml'),

  -- Bluesky公式アカウント(2026-07-06 実在確認済み。運用実績のある公式ドメインハンドルのみ採用)。
  ('Vercel (Bluesky)', 'bluesky', 'https://bsky.app/profile/vercel.com'),
  ('Next.js (Bluesky)', 'bluesky', 'https://bsky.app/profile/nextjs.org'),
  ('Anthropic (Bluesky)', 'bluesky', 'https://bsky.app/profile/anthropic.com'),
  ('GitHub (Bluesky)', 'bluesky', 'https://bsky.app/profile/github.com'),
  ('Bun (Bluesky)', 'bluesky', 'https://bsky.app/profile/bun.sh'),
  ('Cloudflare (Bluesky)', 'bluesky', 'https://bsky.app/profile/cloudflare.social'),
  ('Deno (Bluesky)', 'bluesky', 'https://bsky.app/profile/deno.land'),
  ('TypeScript (Bluesky)', 'bluesky', 'https://bsky.app/profile/typescriptlang.org'),
  ('React (Bluesky)', 'bluesky', 'https://bsky.app/profile/react.dev'),
  ('AWS (Bluesky)', 'bluesky', 'https://bsky.app/profile/awscloud.bsky.social'),

  -- Hacker News経由で信頼済み公式ドメイン(apps/api/src/lib/trustedDomains.ts)の記事を発見する。
  ('Hacker News (trusted domains)', 'hn_domain', 'https://hn.algolia.com/api/v1/search_by_date?tags=story'),

  -- 2026-07-07 追加: 主要な言語・実行環境・フレームワーク・ライブラリの公式リリース/ブログ(全件動作確認済み)。
  ('Python', 'github_releases', 'https://github.com/python/cpython/releases.atom'),
  ('Rust', 'github_releases', 'https://github.com/rust-lang/rust/releases.atom'),
  ('Node.js', 'github_releases', 'https://github.com/nodejs/node/releases.atom'),
  ('Ruby', 'github_releases', 'https://github.com/ruby/ruby/releases.atom'),
  ('PHP', 'github_releases', 'https://github.com/php/php-src/releases.atom'),
  ('Kotlin', 'github_releases', 'https://github.com/JetBrains/kotlin/releases.atom'),
  ('Swift', 'github_releases', 'https://github.com/swiftlang/swift/releases.atom'),
  ('.NET', 'github_releases', 'https://github.com/dotnet/core/releases.atom'),
  ('Elixir', 'github_releases', 'https://github.com/elixir-lang/elixir/releases.atom'),
  ('Zig', 'github_releases', 'https://github.com/ziglang/zig/releases.atom'),
  ('Julia', 'github_releases', 'https://github.com/JuliaLang/julia/releases.atom'),
  ('Go Blog', 'atom', 'https://go.dev/blog/feed.atom'),
  ('Ruby News', 'rss', 'https://www.ruby-lang.org/en/feeds/news.rss'),
  ('Vue', 'github_releases', 'https://github.com/vuejs/core/releases.atom'),
  ('Svelte', 'github_releases', 'https://github.com/sveltejs/svelte/releases.atom'),
  ('Angular', 'github_releases', 'https://github.com/angular/angular/releases.atom'),
  ('SolidJS', 'github_releases', 'https://github.com/solidjs/solid/releases.atom'),
  ('Astro', 'github_releases', 'https://github.com/withastro/astro/releases.atom'),
  ('Remix', 'github_releases', 'https://github.com/remix-run/remix/releases.atom'),
  ('Nuxt', 'github_releases', 'https://github.com/nuxt/nuxt/releases.atom'),
  ('Qwik', 'github_releases', 'https://github.com/QwikDev/qwik/releases.atom'),
  ('Django', 'github_releases', 'https://github.com/django/django/releases.atom'),
  ('Django Blog', 'rss', 'https://www.djangoproject.com/rss/weblog/'),
  ('Rails', 'github_releases', 'https://github.com/rails/rails/releases.atom'),
  ('NestJS', 'github_releases', 'https://github.com/nestjs/nest/releases.atom'),
  ('Spring Blog', 'atom', 'https://spring.io/blog.atom'),
  ('PostgreSQL News', 'rss', 'https://www.postgresql.org/news.rss'),
  ('Redis', 'github_releases', 'https://github.com/redis/redis/releases.atom'),
  ('Redis Blog', 'rss', 'https://redis.io/blog/feed/'),
  ('Supabase', 'github_releases', 'https://github.com/supabase/supabase/releases.atom'),
  ('Kubernetes', 'github_releases', 'https://github.com/kubernetes/kubernetes/releases.atom'),
  ('Kubernetes Blog', 'rss', 'https://kubernetes.io/feed.xml'),
  ('Docker (Moby)', 'github_releases', 'https://github.com/moby/moby/releases.atom'),
  ('Docker Blog', 'rss', 'https://www.docker.com/feed/'),
  ('Terraform', 'github_releases', 'https://github.com/hashicorp/terraform/releases.atom'),
  ('Google Cloud Blog', 'rss', 'https://docs.cloud.google.com/feeds/gcp-release-notes.xml'),
  ('Azure Blog', 'rss', 'https://azure.microsoft.com/en-us/blog/feed/'),
  ('GitLab Blog', 'atom', 'https://about.gitlab.com/atom.xml'),
  ('Hugging Face Blog', 'atom', 'https://huggingface.co/blog/feed.xml'),
  ('Google DeepMind Blog', 'rss', 'https://deepmind.google/blog/rss.xml'),
  ('Vite', 'github_releases', 'https://github.com/vitejs/vite/releases.atom'),
  ('esbuild', 'github_releases', 'https://github.com/evanw/esbuild/releases.atom'),
  ('Webpack', 'github_releases', 'https://github.com/webpack/webpack/releases.atom'),
  ('Turborepo', 'github_releases', 'https://github.com/vercel/turborepo/releases.atom'),
  ('Rollup', 'github_releases', 'https://github.com/rollup/rollup/releases.atom'),
  ('Jest', 'github_releases', 'https://github.com/jestjs/jest/releases.atom'),
  ('Vitest', 'github_releases', 'https://github.com/vitest-dev/vitest/releases.atom'),
  ('Playwright', 'github_releases', 'https://github.com/microsoft/playwright/releases.atom'),
  ('Cypress', 'github_releases', 'https://github.com/cypress-io/cypress/releases.atom'),

  -- 2026-07-07 追加(2): Pythonエコシステム、CSSフレームワーク、コンポーネントライブラリ、老舗技術。
  ('Flask', 'github_releases', 'https://github.com/pallets/flask/releases.atom'),
  ('FastAPI', 'github_releases', 'https://github.com/fastapi/fastapi/releases.atom'),
  ('Celery', 'github_releases', 'https://github.com/celery/celery/releases.atom'),
  ('SQLAlchemy', 'github_releases', 'https://github.com/sqlalchemy/sqlalchemy/releases.atom'),
  ('Pydantic', 'github_releases', 'https://github.com/pydantic/pydantic/releases.atom'),
  ('NumPy', 'github_releases', 'https://github.com/numpy/numpy/releases.atom'),
  ('pandas', 'github_releases', 'https://github.com/pandas-dev/pandas/releases.atom'),
  ('PyTorch', 'github_releases', 'https://github.com/pytorch/pytorch/releases.atom'),
  ('TensorFlow', 'github_releases', 'https://github.com/tensorflow/tensorflow/releases.atom'),
  ('scikit-learn', 'github_releases', 'https://github.com/scikit-learn/scikit-learn/releases.atom'),
  ('Poetry', 'github_releases', 'https://github.com/python-poetry/poetry/releases.atom'),
  ('pytest', 'github_releases', 'https://github.com/pytest-dev/pytest/releases.atom'),
  ('Airflow', 'github_releases', 'https://github.com/apache/airflow/releases.atom'),
  ('JupyterLab', 'github_releases', 'https://github.com/jupyterlab/jupyterlab/releases.atom'),
  ('Ruff', 'github_releases', 'https://github.com/astral-sh/ruff/releases.atom'),
  ('uv', 'github_releases', 'https://github.com/astral-sh/uv/releases.atom'),
  ('Tailwind CSS', 'github_releases', 'https://github.com/tailwindlabs/tailwindcss/releases.atom'),
  ('Bootstrap', 'github_releases', 'https://github.com/twbs/bootstrap/releases.atom'),
  ('Bulma', 'github_releases', 'https://github.com/jgthms/bulma/releases.atom'),
  ('Foundation', 'github_releases', 'https://github.com/foundation/foundation-sites/releases.atom'),
  ('UnoCSS', 'github_releases', 'https://github.com/unocss/unocss/releases.atom'),
  ('shadcn/ui', 'github_releases', 'https://github.com/shadcn-ui/ui/releases.atom'),
  ('Material UI', 'github_releases', 'https://github.com/mui/material-ui/releases.atom'),
  ('Ant Design', 'github_releases', 'https://github.com/ant-design/ant-design/releases.atom'),
  ('Chakra UI', 'github_releases', 'https://github.com/chakra-ui/chakra-ui/releases.atom'),
  ('Headless UI', 'github_releases', 'https://github.com/tailwindlabs/headlessui/releases.atom'),
  ('Mantine', 'github_releases', 'https://github.com/mantinedev/mantine/releases.atom'),
  ('daisyUI', 'github_releases', 'https://github.com/saadeghi/daisyui/releases.atom'),
  ('PrimeVue', 'github_releases', 'https://github.com/primefaces/primevue/releases.atom'),
  ('PrimeReact', 'github_releases', 'https://github.com/primefaces/primereact/releases.atom'),
  ('Git', 'github_releases', 'https://github.com/git/git/releases.atom'),
  ('Vim', 'github_releases', 'https://github.com/vim/vim/releases.atom'),
  ('Neovim', 'github_releases', 'https://github.com/neovim/neovim/releases.atom'),
  ('LLVM', 'github_releases', 'https://github.com/llvm/llvm-project/releases.atom'),
  ('nginx', 'github_releases', 'https://github.com/nginx/nginx/releases.atom'),
  ('Apache HTTP Server', 'github_releases', 'https://github.com/apache/httpd/releases.atom'),
  ('Lodash', 'github_releases', 'https://github.com/lodash/lodash/releases.atom'),
  ('date-fns', 'github_releases', 'https://github.com/date-fns/date-fns/releases.atom'),
  ('Zod', 'github_releases', 'https://github.com/colinhacks/zod/releases.atom'),
  ('Prisma', 'github_releases', 'https://github.com/prisma/prisma/releases.atom'),
  ('Drizzle ORM', 'github_releases', 'https://github.com/drizzle-team/drizzle-orm/releases.atom'),
  ('tRPC', 'github_releases', 'https://github.com/trpc/trpc/releases.atom'),
  ('GraphQL', 'github_releases', 'https://github.com/graphql/graphql-js/releases.atom'),
  ('Apollo Client', 'github_releases', 'https://github.com/apollographql/apollo-client/releases.atom'),
  ('Framer Motion', 'github_releases', 'https://github.com/motiondivision/motion/releases.atom'),
  ('Storybook', 'github_releases', 'https://github.com/storybookjs/storybook/releases.atom'),
  ('ESLint', 'github_releases', 'https://github.com/eslint/eslint/releases.atom'),
  ('Prettier', 'github_releases', 'https://github.com/prettier/prettier/releases.atom'),
  ('Biome', 'github_releases', 'https://github.com/biomejs/biome/releases.atom'),
  ('pnpm', 'github_releases', 'https://github.com/pnpm/pnpm/releases.atom'),
  ('Yarn', 'github_releases', 'https://github.com/yarnpkg/berry/releases.atom'),

  -- 2026-07-07 追加(3): モバイル、状態管理、ゲームエンジン、CI/CD、監視、MQ、検索、SSG、AI/MLツール、その他言語。
  ('React Native', 'github_releases', 'https://github.com/react/react-native/releases.atom'),
  ('Flutter', 'github_releases', 'https://github.com/flutter/flutter/releases.atom'),
  ('Ionic', 'github_releases', 'https://github.com/ionic-team/ionic-framework/releases.atom'),
  ('Redux', 'github_releases', 'https://github.com/reduxjs/redux/releases.atom'),
  ('Zustand', 'github_releases', 'https://github.com/pmndrs/zustand/releases.atom'),
  ('Pinia', 'github_releases', 'https://github.com/vuejs/pinia/releases.atom'),
  ('MobX', 'github_releases', 'https://github.com/mobxjs/mobx/releases.atom'),
  ('Jotai', 'github_releases', 'https://github.com/pmndrs/jotai/releases.atom'),
  ('TanStack Query', 'github_releases', 'https://github.com/TanStack/query/releases.atom'),
  ('Godot Engine', 'github_releases', 'https://github.com/godotengine/godot/releases.atom'),
  ('Bevy', 'github_releases', 'https://github.com/bevyengine/bevy/releases.atom'),
  ('Three.js', 'github_releases', 'https://github.com/mrdoob/three.js/releases.atom'),
  ('Babylon.js', 'github_releases', 'https://github.com/BabylonJS/Babylon.js/releases.atom'),
  ('Jenkins', 'github_releases', 'https://github.com/jenkinsci/jenkins/releases.atom'),
  ('CircleCI CLI', 'github_releases', 'https://github.com/CircleCI-Public/circleci-cli/releases.atom'),
  ('ArgoCD', 'github_releases', 'https://github.com/argoproj/argo-cd/releases.atom'),
  ('Prometheus', 'github_releases', 'https://github.com/prometheus/prometheus/releases.atom'),
  ('Grafana', 'github_releases', 'https://github.com/grafana/grafana/releases.atom'),
  ('OpenTelemetry', 'github_releases', 'https://github.com/open-telemetry/opentelemetry-specification/releases.atom'),
  ('Jaeger', 'github_releases', 'https://github.com/jaegertracing/jaeger/releases.atom'),
  ('Apache Kafka', 'github_releases', 'https://github.com/apache/kafka/releases.atom'),
  ('RabbitMQ', 'github_releases', 'https://github.com/rabbitmq/rabbitmq-server/releases.atom'),
  ('NATS', 'github_releases', 'https://github.com/nats-io/nats-server/releases.atom'),
  ('Elasticsearch', 'github_releases', 'https://github.com/elastic/elasticsearch/releases.atom'),
  ('Meilisearch', 'github_releases', 'https://github.com/meilisearch/meilisearch/releases.atom'),
  ('Typesense', 'github_releases', 'https://github.com/typesense/typesense/releases.atom'),
  ('Hugo', 'github_releases', 'https://github.com/gohugoio/hugo/releases.atom'),
  ('Eleventy', 'github_releases', 'https://github.com/11ty/buildawesome/releases.atom'),
  ('Gatsby', 'github_releases', 'https://github.com/gatsbyjs/gatsby/releases.atom'),
  ('Jekyll', 'github_releases', 'https://github.com/jekyll/jekyll/releases.atom'),
  ('Docusaurus', 'github_releases', 'https://github.com/facebook/docusaurus/releases.atom'),
  ('LangChain', 'github_releases', 'https://github.com/langchain-ai/langchain/releases.atom'),
  ('vLLM', 'github_releases', 'https://github.com/vllm-project/vllm/releases.atom'),
  ('Ollama', 'github_releases', 'https://github.com/ollama/ollama/releases.atom'),
  ('LlamaIndex', 'github_releases', 'https://github.com/run-llama/llama_index/releases.atom'),
  ('Transformers (Hugging Face)', 'github_releases', 'https://github.com/huggingface/transformers/releases.atom'),
  ('Haskell (GHC)', 'github_releases', 'https://github.com/ghc/ghc/releases.atom'),
  ('Scala', 'github_releases', 'https://github.com/scala/scala/releases.atom'),
  ('Clojure', 'github_releases', 'https://github.com/clojure/clojure/releases.atom'),
  ('Dart', 'github_releases', 'https://github.com/dart-lang/sdk/releases.atom'),
  ('Lua', 'github_releases', 'https://github.com/lua/lua/releases.atom'),
  ('Crystal', 'github_releases', 'https://github.com/crystal-lang/crystal/releases.atom'),
  ('Nim', 'github_releases', 'https://github.com/nim-lang/Nim/releases.atom'),
  ('OCaml', 'github_releases', 'https://github.com/ocaml/ocaml/releases.atom'),
  ('Erlang/OTP', 'github_releases', 'https://github.com/erlang/otp/releases.atom')
on conflict (url) do nothing;

insert into topics (slug, name_ja, name_en) values
  ('frontend', 'フロントエンド', 'Frontend'),
  ('nextjs', 'Next.js', 'Next.js'),
  ('react', 'React', 'React'),
  ('typescript', 'TypeScript', 'TypeScript'),
  ('javascript', 'JavaScript', 'JavaScript'),
  ('nodejs', 'Node.js / ランタイム', 'Node.js / Runtimes'),
  ('ai-llm', 'AI・LLM', 'AI & LLM'),
  ('dev-tools', '開発ツール', 'Developer Tools'),
  ('cloud', 'クラウド', 'Cloud'),
  ('aws', 'AWS', 'AWS'),
  ('cloudflare', 'Cloudflare', 'Cloudflare'),
  ('serverless', 'サーバーレス', 'Serverless'),
  ('devops', 'DevOps・CI/CD', 'DevOps & CI/CD'),
  ('security', 'セキュリティ', 'Security'),
  ('database', 'データベース', 'Database'),
  ('opensource', 'オープンソース', 'Open Source'),
  ('testing', 'テスト', 'Testing'),
  ('mobile', 'モバイル', 'Mobile')
on conflict (slug) do nothing;
